### PR TITLE
Fix #29 — Fetch paginated responses completely

### LINKED ISSUE #29: Only first page of API results returned
DigitalOcean paginates their results, returning a default of 20 and max of 200 entries. When requesting a list of my 48 droplets, only 20 are returned. I have only confirmed this with droplet requests, but I'm sure it affects others as well.

https://developers.digitalocean.com/documentation/changelog/api-v2/tweak-per-page/

Here is an example of curl requests against the API with and without the per_page option:
```
ryan@ops-server:dopy$ curl -s -X GET -H "Authorization: Bearer $TOKEN" \
"https://api.digitalocean.com/v2/droplets" \
| python -m json.tool | grep version | wc -l
20
```
```
ryan@ops-server:dopy$ curl -s -X GET -H "Authorization: Bearer $TOKEN" \
"https://api.digitalocean.com/v2/droplets?per_page=100" \
| python -m json.tool | grep version | wc -l
48
```

I'm a python novice but am doing some testing to see if I can implement this.

### PR DESCRIPTION
**Pull request by Xowap**
As stated in #29, only the first page of response was fetched (which is a bug and not a bloody enhancement, btw).

This PR fixes that with a decorator around the `request_v2()` method which, in case of `GET` request, will parse the output, find next page if required and will append the content to the current content.

I can't guarantee I didn't break anything due to the lack of unit tests, but my Ansible script still works.

Also, this project's code seriously requires to get through PEP 8 linting, but that's none of my business.

### CODE REVIEW

**Comment by jeremykendall** [comment]
Bump. I have > 200 droplets and just broke my dynamic inventory script by upgrading to DigitalOcean API V2.

@Xowap 100% agree: #29 is a bug, not an enhancement request.

**Comment by haz-mat** [comment]
+1, would be great to have this fix pulled.

**Comment by kmadac** [comment]
+1, pull this request please

**Comment by whiskybar** [comment]
+1, we need this urgently as Digital Ocean API v1 has been deprecated as of today:

https://developers.digitalocean.com/documentation/v1/

**Comment by zbal** [comment]
Thanks - PR Merged - will release to pip later on today.

**Comment by Xowap** [comment]
Good :+1:

**Pull request merged**
